spring.application.name=backend
server.port=8080

# Activate the H2 Database Dashboard
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Saves database files directly inside a 'data' folder in your project
spring.datasource.url=jdbc:h2:file:./data/pghub_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate Database setup
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
hibernate.validator.apply_to_ddl=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB